name: 'markdownlint'
description: 'Run the ruby markdownlint'
inputs:
  parameters:  # id of input
    description: 'parameters for markdownlint'
    required: false
    default: '--help'
outputs:
  log: # id of the output
    description: 'the markdownlint logs'
runs:
  using: 'docker'
  image: 'action.Dockerfile'
